    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Functions.fondAcceso;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryyv
 */
public class Acceso extends javax.swing.JFrame {
public InputStream acceso = this.getClass().getResourceAsStream("/Resources/frmacceso.png");
Main main;
JIFPrestamo prestamo;
Functions.Functions cnn = new Functions.Functions();
String psw = "";
Functions.Functions conexion;

    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
        cargarImagen(dtpAcceso, acceso);
        this.setLocationRelativeTo(null);
        txtLogin.setBackground(Color.darkGray);
        txtLogin.setForeground(Color.white);
        txtLogin.requestFocus();
    }
    
    public void cargarImagen(javax.swing.JDesktopPane jDeskp, InputStream fileImagen) {
        try {
            BufferedImage image = ImageIO.read(fileImagen);
            jDeskp.setBorder(new fondAcceso(image));
        } catch (Exception e) {
            System.out.println("Imagen no disponible");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpAcceso = new javax.swing.JDesktopPane();
        btnAcceder = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        psfPassword = new javax.swing.JPasswordField();
        txtLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);

        dtpAcceso.setOpaque(false);

        btnAcceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/aceptar.png"))); // NOI18N
        btnAcceder.setText("Ingresar");
        btnAcceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logout.png"))); // NOI18N
        btnSalir.setText("Cancelar");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 153));
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 153));
        jLabel2.setText("Password");

        psfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psfPassword.setEchoChar('\u2022');
        psfPassword.setNextFocusableComponent(btnAcceder);
        psfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                psfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                psfPasswordFocusLost(evt);
            }
        });
        psfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                psfPasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                psfPasswordKeyTyped(evt);
            }
        });

        txtLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtLogin.setNextFocusableComponent(psfPassword);
        txtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLoginFocusLost(evt);
            }
        });
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoginKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLoginKeyTyped(evt);
            }
        });

        dtpAcceso.setLayer(btnAcceder, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dtpAcceso.setLayer(btnSalir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dtpAcceso.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dtpAcceso.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dtpAcceso.setLayer(psfPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dtpAcceso.setLayer(txtLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dtpAccesoLayout = new javax.swing.GroupLayout(dtpAcceso);
        dtpAcceso.setLayout(dtpAccesoLayout);
        dtpAccesoLayout.setHorizontalGroup(
            dtpAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dtpAccesoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dtpAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAcceder, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(dtpAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(psfPassword)
                    .addComponent(txtLogin))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        dtpAccesoLayout.setVerticalGroup(
            dtpAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dtpAccesoLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(dtpAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dtpAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(psfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(dtpAccesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceder)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpAcceso)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpAcceso)
        );

        dtpAcceso.getAccessibleContext().setAccessibleParent(psfPassword);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    public void login(String user, String password) throws SQLException {
        try {
            String sql = "SELECT * FROM usuario WHERE login = '" + user + "' AND pass = '" + password + "'";
            String acceso = "";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                acceso = "1";
            }
            if (acceso == "1") {
                main = new Main();
                main.setVisible(true);
                this.dispose();
            } else {
                this.hide();
                JOptionPane.showMessageDialog(null, "Ingrese nuevamente los datos correctos");
                this.show();
                psfPassword.setText("");
                txtLogin.selectAll();
                txtLogin.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Acceso.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        char clave[] = psfPassword.getPassword();
        String Password = new String(clave);
        if (txtLogin.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese su usuario");
            txtLogin.requestFocus();
        } if (psfPassword.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese contraseña");
            psfPassword.requestFocus();
        } else {
            try {
                login(txtLogin.getText(), Password);
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
                
            }
        }
    }//GEN-LAST:event_btnAccederActionPerformed

    private void txtLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusGained
        txtLogin.setBackground(Color.darkGray);
        txtLogin.setForeground(Color.white);
        txtLogin.selectAll();
    }//GEN-LAST:event_txtLoginFocusGained

    private void txtLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusLost
        txtLogin.setBackground(Color.white);
        txtLogin.setForeground(Color.black);
    }//GEN-LAST:event_txtLoginFocusLost

    private void psfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_psfPasswordFocusGained
        psfPassword.setBackground(Color.darkGray);
        psfPassword.setForeground(Color.white);
        psfPassword.selectAll();
    }//GEN-LAST:event_psfPasswordFocusGained

    private void psfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_psfPasswordFocusLost
        psfPassword.setBackground(Color.white);
        psfPassword.setForeground(Color.black);
    }//GEN-LAST:event_psfPasswordFocusLost

    private void txtLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter != '\b' && !Character.isLetter(caracter) || txtLogin.getText().length() >= 20) {
            evt.consume();
        } else {
            if (Character.isLowerCase(caracter)) {
                String cad = ("" + caracter).toUpperCase();
                caracter = cad.charAt(0);
                evt.setKeyChar(caracter);
            }
        }
    }//GEN-LAST:event_txtLoginKeyTyped

    private void txtLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            psfPassword.requestFocus();
        }
    }//GEN-LAST:event_txtLoginKeyPressed

    private void psfPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psfPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAcceder.doClick();
        }
    }//GEN-LAST:event_psfPasswordKeyPressed

    private void psfPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_psfPasswordKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9' && caracter != '\b' || psfPassword.getText().length() >= 8) {
            evt.consume();
        }
    }//GEN-LAST:event_psfPasswordKeyTyped
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PortadaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PortadaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PortadaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PortadaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        new Thread(new SplashScreen()).start();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(false);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnSalir;
    private javax.swing.JDesktopPane dtpAcceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField psfPassword;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
