/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Functions.Functions;
import static Presentation.Main.dtpMain;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Bryyv
 */
public class JIFBookAdd extends javax.swing.JInternalFrame {
    File fichero;
    Functions cnn = new Functions();
    java.sql.Statement st;
    java.sql.ResultSet rs;
    JIFBookShow bookshow;
    FrmAutorAdd autoradd;
    
    /**
     * Creates new form JIFNewBook
     */
    public JIFBookAdd() {
        initComponents();
        cargareditoriales();
        cargarmaterias();
    }
    
    public void cargareditoriales() {
        try {
            String sql = "SELECT nombre FROM editorial ORDER BY edit_id";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()) {
                cboEditorial.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void cargarmaterias() {
        try {
            String sql = "SELECT nombre FROM materia ORDER BY nombre";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()) {
                cboMateria.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage().toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboEditorial = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        cboMateria = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtCantPags = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaContenidos = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPortada = new javax.swing.JLabel();
        btnPortada = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        cboTipoLibro = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        cboAutores = new javax.swing.JComboBox<>();
        btnAutores = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar nuevo libro");

        pnDatos.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("Título del libro");

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del autor");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("Editorial");

        cboEditorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cboEditorial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboEditorialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboEditorialFocusLost(evt);
            }
        });
        cboEditorial.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboEditorialPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel7.setText("ISBN");

        txtIsbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIsbnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIsbnFocusLost(evt);
            }
        });
        txtIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIsbnKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIsbnKeyTyped(evt);
            }
        });

        cboMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cboMateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboMateriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboMateriaFocusLost(evt);
            }
        });
        cboMateria.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboMateriaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel12.setText("Materia");

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("Lugar de publicación");

        txtLugar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLugarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLugarFocusLost(evt);
            }
        });
        txtLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLugarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLugarKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setText("Año de publicación");

        txtYear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtYearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtYearFocusLost(evt);
            }
        });
        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtYearKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYearKeyTyped(evt);
            }
        });

        txtCantPags.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCantPags.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantPagsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantPagsFocusLost(evt);
            }
        });
        txtCantPags.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantPagsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantPagsKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("Cantidad de páginas");

        txtCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodeFocusLost(evt);
            }
        });
        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodeKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel9.setText("Código");

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel10.setText("Contenidos");

        txaContenidos.setColumns(20);
        txaContenidos.setRows(50);
        jScrollPane1.setViewportView(txaContenidos);

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel14.setText("Portada");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblPortada.setFont(new java.awt.Font("Edwardian Script ITC", 0, 36)); // NOI18N
        lblPortada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPortada.setText("Portada");
        lblPortada.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPortada.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/imagen.png"))); // NOI18N
        btnPortada.setText("Cargar imagen");
        btnPortada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPortadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPortada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPortada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPortada)
                .addContainerGap())
        );

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel15.setText("Tipo de libro");

        cboTipoLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "PÚBLICO EN GENERAL", "MAYORES DE 14", "MAYORES DE 18" }));
        cboTipoLibro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboTipoLibroFocusGained(evt);
            }
        });
        cboTipoLibro.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboTipoLibroPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/volver.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAutores.setText("...");
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDatosLayout = new javax.swing.GroupLayout(pnDatos);
        pnDatos.setLayout(pnDatosLayout);
        pnDatosLayout.setHorizontalGroup(
            pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDatosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addGroup(pnDatosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnAutores)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboEditorial, 0, 400, Short.MAX_VALUE)
                    .addComponent(txtIsbn)
                    .addComponent(txtNombre)
                    .addComponent(cboAutores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDatosLayout.createSequentialGroup()
                        .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(45, 45, 45)
                        .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantPags, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1)
                            .addComponent(cboTipoLibro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCode)))
                    .addGroup(pnDatosLayout.createSequentialGroup()
                        .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addGap(37, 37, 37)
                        .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnDatosLayout.createSequentialGroup()
                                .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(pnDatosLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        pnDatosLayout.setVerticalGroup(
            pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDatosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel12)
                    .addComponent(cboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cboAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutores))
                .addGap(18, 18, 18)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCantPags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDatosLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnDatosLayout.createSequentialGroup()
                        .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDatosLayout.createSequentialGroup()
                                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAutores.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtIsbnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnPortada.requestFocus();
        }
    }//GEN-LAST:event_txtIsbnKeyPressed

    private void txtLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtYear.requestFocus();
        }
    }//GEN-LAST:event_txtLugarKeyPressed

    private void txtYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCantPags.requestFocus();
        }
    }//GEN-LAST:event_txtYearKeyPressed

    private void txtCantPagsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantPagsKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtCode.requestFocus();
        }
    }//GEN-LAST:event_txtCantPagsKeyPressed

    private void txtCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cboTipoLibro.requestFocus();
        }
    }//GEN-LAST:event_txtCodeKeyPressed

    private void txtYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9' && caracter != '\b' || txtYear.getText().length() == 4){
            evt.consume();
        }
    }//GEN-LAST:event_txtYearKeyTyped

    private void txtCantPagsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantPagsKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9' && caracter != '\b' || txtCantPags.getText().length() == 4){
            evt.consume();
        }
    }//GEN-LAST:event_txtCantPagsKeyTyped

    private void cboEditorialPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboEditorialPopupMenuWillBecomeInvisible
        txtIsbn.requestFocus();
    }//GEN-LAST:event_cboEditorialPopupMenuWillBecomeInvisible

    private void cboMateriaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboMateriaPopupMenuWillBecomeInvisible
        txtLugar.requestFocus();
    }//GEN-LAST:event_cboMateriaPopupMenuWillBecomeInvisible

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Logic.DAOLibro obj = new Logic.DAOLibro();
        obj.setLib_id(txtCode.getText());
        obj.setTitulo(txtNombre.getText());
        obj.setCant_pags(Integer.parseInt(txtCantPags.getText()));
        obj.setYear_pub(Integer.parseInt(txtYear.getText()));
        obj.setIsbn(txtIsbn.getText());
        obj.setPortada(fichero.toString());
        obj.setLug_pub(txtLugar.getText());
        obj.setContenidos(txaContenidos.getText());
        obj.setTipo_libro(cboTipoLibro.getSelectedItem().toString());
        obj.setEdit_id(cboEditorial.getSelectedIndex());
        obj.setMateria(cboMateria.getSelectedItem().toString());
        if (obj.insertar_libro() == true) {
            JOptionPane.showMessageDialog(rootPane, "Registro ingresado con éxito");
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se consiguó insertar");
        }
        int lon = cboAutores.getItemCount();
        for (int i = 0; i < lon; i++) {
            String subcadena = cboAutores.getItemAt(i).substring(1, 6);
            System.out.println(subcadena);
            obj.setAut_id(Integer.parseInt(subcadena));
            obj.setLib_id(txtCode.getText());
            if (obj.insertar_escrito() == true) {
                System.out.println("Autor ingresado con éxito");
            } else {
                System.out.println("Autor no ingresado");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtNombre.setText("");
        cboAutores.setSelectedIndex(-1);
        cboEditorial.setSelectedItem("...");
        txtIsbn.setText("");
        cboMateria.setSelectedItem("...");
        txtLugar.setText("");
        txtYear.setText("");
        txtCantPags.setText("");
        txtCode.setText("");
        txaContenidos.setText("");
        lblPortada.setIcon(null);
        lblPortada.setText("Portada");
        cboTipoLibro.setSelectedItem("...");
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        txtNombre.setBackground(Color.darkGray);
        txtNombre.setForeground(Color.white);
        txtNombre.selectAll();
    }//GEN-LAST:event_txtNombreFocusGained

    private void cboEditorialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboEditorialFocusGained
        
    }//GEN-LAST:event_cboEditorialFocusGained

    private void txtIsbnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIsbnFocusGained
        txtIsbn.setBackground(Color.darkGray);
        txtIsbn.setForeground(Color.white);
        txtIsbn.selectAll();
    }//GEN-LAST:event_txtIsbnFocusGained

    private void cboMateriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboMateriaFocusGained
        
    }//GEN-LAST:event_cboMateriaFocusGained

    private void txtLugarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLugarFocusGained
        txtLugar.setBackground(Color.darkGray);
        txtLugar.setForeground(Color.white);
        txtLugar.selectAll();
    }//GEN-LAST:event_txtLugarFocusGained

    private void txtYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearFocusGained
        txtYear.setBackground(Color.darkGray);
        txtYear.setForeground(Color.white);
        txtYear.selectAll();
    }//GEN-LAST:event_txtYearFocusGained

    private void txtCantPagsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantPagsFocusGained
        txtCantPags.setBackground(Color.darkGray);
        txtCantPags.setBackground(Color.white);
        txtCantPags.selectAll();
    }//GEN-LAST:event_txtCantPagsFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        txtNombre.setBackground(Color.white);
        txtNombre.setForeground(Color.black);
    }//GEN-LAST:event_txtNombreFocusLost

    private void cboEditorialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboEditorialFocusLost
        
    }//GEN-LAST:event_cboEditorialFocusLost

    private void txtIsbnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIsbnFocusLost
        txtIsbn.setBackground(Color.white);
        txtIsbn.setForeground(Color.black);
    }//GEN-LAST:event_txtIsbnFocusLost

    private void cboMateriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboMateriaFocusLost
        
    }//GEN-LAST:event_cboMateriaFocusLost

    private void txtLugarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLugarFocusLost
        txtLugar.setBackground(Color.white);
        txtLugar.setForeground(Color.black);
    }//GEN-LAST:event_txtLugarFocusLost

    private void txtYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearFocusLost
        txtYear.setBackground(Color.white);
        txtYear.setForeground(Color.black);
    }//GEN-LAST:event_txtYearFocusLost

    private void txtCantPagsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantPagsFocusLost
        txtCantPags.setBackground(Color.white);
        txtCantPags.setForeground(Color.black);
    }//GEN-LAST:event_txtCantPagsFocusLost

    private void btnPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPortadaActionPerformed
        int resultado;
        PortadaAdd portada = new PortadaAdd();
        //establece filtro para cargar solo ese formato de archivos
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");
        //establece el filtro en el JFileChooser
        portada.fchPortada.setFileFilter(filtro);
        //abre la ventana
        resultado = portada.fchPortada.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero = portada.fchPortada.getSelectedFile();
            try {
                ImageIcon icon = new ImageIcon(fichero.toString());
                //autoajuste al control que contendrá la imagen
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblPortada.getWidth(), lblPortada.getHeight(), Image.SCALE_DEFAULT));
                lblPortada.setText(null);
                lblPortada.setIcon(icono);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Error abriendo la imagen" + e);
            }
        }
    }//GEN-LAST:event_btnPortadaActionPerformed

    private void cboTipoLibroPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboTipoLibroPopupMenuWillBecomeInvisible
        txaContenidos.requestFocus();
    }//GEN-LAST:event_cboTipoLibroPopupMenuWillBecomeInvisible

    private void txtIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9' || txtIsbn.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIsbnKeyTyped

    private void txtCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodeFocusGained
        txtCode.setBackground(Color.darkGray);
        txtCode.setForeground(Color.white);
        txtCode.selectAll();
    }//GEN-LAST:event_txtCodeFocusGained

    private void txtCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodeFocusLost
        txtCode.setBackground(Color.white);
        txtCode.setForeground(Color.black);
    }//GEN-LAST:event_txtCodeFocusLost

    private void txtCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter != KeyEvent.VK_PERIOD && txtCode.getText().length() >= 20 && caracter < '0' || caracter > '9' && (!Character.isLetter(caracter)) || txtCode.getText().length() >= 20) {
            evt.consume();
        } else {
            if (Character.isLowerCase(caracter)) {
                String cad = ("" + caracter).toUpperCase();
                caracter = cad.charAt(0);
                evt.setKeyChar(caracter);
            }
        }
    }//GEN-LAST:event_txtCodeKeyTyped

    private void txtLugarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter != '\b' && (!Character.isLetter(caracter)) && caracter != KeyEvent.VK_SPACE) {
            evt.consume();
        } else {
            if (Character.isLowerCase(caracter)) {
                String cad = ("" + caracter).toUpperCase();
                caracter = cad.charAt(0);
                evt.setKeyChar(caracter);
            }
        }
    }//GEN-LAST:event_txtLugarKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char caracter = evt.getKeyChar();
        if (Character.isLowerCase(caracter)) {
            String cad = ("" + caracter).toUpperCase();
            caracter = cad.charAt(0);
            evt.setKeyChar(caracter);
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void cboTipoLibroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboTipoLibroFocusGained
        
    }//GEN-LAST:event_cboTipoLibroFocusGained

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
        autoradd = new FrmAutorAdd();
        Dimension ds = Main.dtpMain.getSize();
        Dimension fs = autoradd.getSize();
        autoradd.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
        autoradd.show();
        txtNombre.setEnabled(false);
        btnAutores.setEnabled(false);
        cboAutores.setEnabled(false);
        cboEditorial.setEnabled(false);
        txtIsbn.setEnabled(false);
        btnPortada.setEnabled(false);
        cboMateria.setEnabled(false);
        txtLugar.setEnabled(false);
        txtYear.setEnabled(false);
        txtCantPags.setEnabled(false);
        txtCode.setEnabled(false);
        cboTipoLibro.setEnabled(false);
        txaContenidos.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnSalir.setEnabled(false);
    }//GEN-LAST:event_btnAutoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAutores;
    public static javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnGuardar;
    public static javax.swing.JButton btnPortada;
    public static javax.swing.JButton btnSalir;
    public static javax.swing.JComboBox<String> cboAutores;
    public static javax.swing.JComboBox<String> cboEditorial;
    public static javax.swing.JComboBox<String> cboMateria;
    public static javax.swing.JComboBox<String> cboTipoLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPortada;
    public static javax.swing.JPanel pnDatos;
    public static javax.swing.JTextArea txaContenidos;
    public static javax.swing.JTextField txtCantPags;
    public static javax.swing.JTextField txtCode;
    public static javax.swing.JTextField txtIsbn;
    public static javax.swing.JTextField txtLugar;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    
}
