/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Functions.Functions;
import static Presentation.Main.dtpMain;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Bryyv
 */
public class JIFBookEdit extends javax.swing.JInternalFrame {
    File fichero;
    Functions cnn = new Functions();
    JIFBookShow bookshow;
    FrmAutorEdit autoredit;

    /**
     * Creates new form JIFBookEdit
     */
    public JIFBookEdit() {
        initComponents();
        cargareditoriales();
        cargarmaterias();
        //cargar_datos(txtCode.getText());
    }
    /*
    public void cargar_datos(String codigo) {
        try {
            String sql = "SELECT libro.titulo, autor.aut_id, autor.apellidos || ' ' || autor.nombres, editorial.nombre, libro.isbn, libro.portada, libro.materia, libro.lug_pub, libro.cant_pags, libro.tipo_libro, libro.contenidos FROM public.autor, public.editorial, public.escrito, public.libro WHERE editorial.edit_id = libro.edit_id AND escrito.lib_id = libro.lib_id AND escrito.aut_id = autor.aut_id AND lib_id = '" + codigo + "'";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()) {
                txtNombre.setText(rs.getString(0));
                cboAutores.addItem(rs.getString(1) + "-" + rs.getString(2));
                cboEditorial.setSelectedItem(rs.getString(3));
                txtIsbn.setText(rs.getString(4));
                try {
                    ImageIcon icon = new ImageIcon(rs.getString(5));
                    //autoajuste al control que contendrá la imagen
                    Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblPortada.getWidth(), lblPortada.getHeight(), Image.SCALE_DEFAULT));
                    lblPortada.setText(null);
                    lblPortada.setIcon(icono);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null,"Error abriendo la imagen" + e);
                }
                cboMateria.setSelectedItem(rs.getString(6));
                txtLugar.setText(rs.getString(7));
                txtYear.setText(rs.getString(8));
                txtCantPags.setText(rs.getString(9));
                txtCode.setEnabled(false);
                cboTipoLibro.setSelectedItem(rs.getString(10));
                txaContenidos.setText(rs.getString(11));
            }
        } catch (SQLException | HeadlessException e) {
            System.out.println(e.getMessage());
        }
    }
    */
    public void cargareditoriales() {
        try {
            String sql = "SELECT nombre FROM editorial ORDER BY edit_id";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()) {
                cboEditorial.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void cargarmaterias() {
        try {
            String sql = "SELECT nombre FROM materia ORDER BY nombre";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()) {
                cboMateria.addItem(rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println(e.getMessage().toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtCantPags = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cboMateria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIsbn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        cboEditorial = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaContenidos = new javax.swing.JTextArea();
        txtCode = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPortada = new javax.swing.JLabel();
        btnPortada = new javax.swing.JButton();
        cboTipoLibro = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cboAutores = new javax.swing.JComboBox<>();
        btnAutores = new javax.swing.JButton();

        setClosable(true);
        setTitle("Modificar Datos de Libro Existente");

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel7.setText("ISBN");

        txtYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtYearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtYearFocusLost(evt);
            }
        });
        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtYearKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYearKeyTyped(evt);
            }
        });

        txtCantPags.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCantPagsFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCantPagsFocusLost(evt);
            }
        });
        txtCantPags.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantPagsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantPagsKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel9.setText("Código");

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel10.setText("Contenidos");

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setText("Título del libro");

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        cboMateria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cboMateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboMateriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboMateriaFocusLost(evt);
            }
        });
        cboMateria.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboMateriaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del autor");

        jLabel3.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3.setText("Editorial");

        txtIsbn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIsbnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIsbnFocusLost(evt);
            }
        });
        txtIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIsbnKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIsbnKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4.setText("Lugar de publicación");

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5.setText("Año de publiación");

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6.setText("Cantidad de páginas");

        txtLugar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLugarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLugarFocusLost(evt);
            }
        });
        txtLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarActionPerformed(evt);
            }
        });
        txtLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLugarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLugarKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel12.setText("Materia");

        btnGuardar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar cambios y salir");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cancelar.png"))); // NOI18N
        btnSalir.setText("Salir sin guardar");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        cboEditorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "..." }));
        cboEditorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboEditorial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboEditorialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cboEditorialFocusLost(evt);
            }
        });
        cboEditorial.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboEditorialPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        txaContenidos.setColumns(1);
        txaContenidos.setRows(25);
        jScrollPane1.setViewportView(txaContenidos);

        txtCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodeFocusLost(evt);
            }
        });
        txtCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodeKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel14.setText("Portada");

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblPortada.setFont(new java.awt.Font("Edwardian Script ITC", 0, 36)); // NOI18N
        lblPortada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPortada.setText("Portada");
        lblPortada.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnPortada.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnPortada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/imagen.png"))); // NOI18N
        btnPortada.setText("Modificar");
        btnPortada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPortada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPortadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPortada, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPortada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboTipoLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "PÚBLICO EN GENERAL", "MAYORES DE 14", "MAYORES DE 18" }));
        cboTipoLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cboTipoLibro.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboTipoLibroPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel15.setText("Tipo de libro");

        btnAutores.setText("...");
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnAutores)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIsbn)
                    .addComponent(txtNombre)
                    .addComponent(cboEditorial, 0, 400, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAutores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel9))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCode)
                            .addComponent(cboTipoLibro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLugar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantPags, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 24, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboAutores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutores))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(txtCantPags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboTipoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel14)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            btnAutores.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void cboEditorialPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboEditorialPopupMenuWillBecomeInvisible
        txtIsbn.requestFocus();
    }//GEN-LAST:event_cboEditorialPopupMenuWillBecomeInvisible

    private void txtIsbnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            btnPortada.requestFocus();
        }
    }//GEN-LAST:event_txtIsbnKeyPressed

    private void cboMateriaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboMateriaPopupMenuWillBecomeInvisible
        txtLugar.requestFocus();
    }//GEN-LAST:event_cboMateriaPopupMenuWillBecomeInvisible

    private void txtLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            txtYear.requestFocus();
        }
    }//GEN-LAST:event_txtLugarKeyPressed

    private void txtYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            txtCantPags.requestFocus();
        }
    }//GEN-LAST:event_txtYearKeyPressed

    private void txtCantPagsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantPagsKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
        }
    }//GEN-LAST:event_txtCantPagsKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Logic.DAOLibro obj = new Logic.DAOLibro();
        obj.setLib_id(txtCode.getText());
        obj.setTitulo(txtNombre.getText());
        obj.setCant_pags(Integer.parseInt(txtCantPags.getText()));
        obj.setYear_pub(Integer.parseInt(txtYear.getText()));
        obj.setIsbn(txtIsbn.getText());
        obj.setPortada(lblPortada.getIcon().toString());
        obj.setLug_pub(txtLugar.getText());
        obj.setContenidos(txaContenidos.getText());
        obj.setTipo_libro(cboTipoLibro.getSelectedItem().toString());
        obj.setEdit_id(cboEditorial.getSelectedIndex());
        obj.setMateria(cboMateria.getSelectedItem().toString());
        if (obj.modificar_libro() == true) {
            JOptionPane.showMessageDialog(rootPane, "Datos modificados correctamente");
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se modificaron los registros");
        }
        int lon = cboAutores.getItemCount();
        for (int i = 0; i < lon; i++) {
            String subcadena = cboAutores.getItemAt(i).substring(1, 6);
            System.out.println(subcadena);
            obj.setAut_id(Integer.parseInt(subcadena));
            obj.setLib_id(txtCode.getText());
            if (obj.modificar_escrito() == true) {
                System.out.println("Autor modificado");
            } else {
                System.out.println("Autor no modificado");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        txtNombre.setBackground(Color.darkGray);
        txtNombre.setForeground(Color.white);
    }//GEN-LAST:event_txtNombreFocusGained

    private void cboEditorialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboEditorialFocusGained
        
    }//GEN-LAST:event_cboEditorialFocusGained

    private void txtIsbnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIsbnFocusGained
        txtIsbn.setBackground(Color.darkGray);
        txtIsbn.setForeground(Color.white);
    }//GEN-LAST:event_txtIsbnFocusGained

    private void cboMateriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboMateriaFocusGained
        
    }//GEN-LAST:event_cboMateriaFocusGained

    private void txtLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarActionPerformed
        txtLugar.setBackground(Color.darkGray);
        txtLugar.setForeground(Color.white);
    }//GEN-LAST:event_txtLugarActionPerformed

    private void txtYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearFocusGained
        txtYear.setBackground(Color.darkGray);
        txtYear.setForeground(Color.white);
    }//GEN-LAST:event_txtYearFocusGained

    private void txtCantPagsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantPagsFocusGained
        txtCantPags.setBackground(Color.darkGray);
        txtCantPags.setForeground(Color.white);
    }//GEN-LAST:event_txtCantPagsFocusGained

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        txtNombre.setBackground(Color.white);
        txtNombre.setForeground(Color.black);
    }//GEN-LAST:event_txtNombreFocusLost

    private void cboEditorialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboEditorialFocusLost
        
    }//GEN-LAST:event_cboEditorialFocusLost

    private void txtIsbnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIsbnFocusLost
        txtIsbn.setBackground(Color.white);
        txtIsbn.setForeground(Color.black);
    }//GEN-LAST:event_txtIsbnFocusLost

    private void cboMateriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboMateriaFocusLost
        
    }//GEN-LAST:event_cboMateriaFocusLost

    private void txtLugarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLugarFocusGained
        txtLugar.setBackground(Color.darkGray);
        txtLugar.setForeground(Color.white);
    }//GEN-LAST:event_txtLugarFocusGained

    private void txtLugarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLugarFocusLost
        txtLugar.setBackground(Color.white);
        txtLugar.setForeground(Color.black);
    }//GEN-LAST:event_txtLugarFocusLost

    private void txtYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearFocusLost
        txtYear.setBackground(Color.white);
        txtYear.setForeground(Color.black);
    }//GEN-LAST:event_txtYearFocusLost

    private void txtCantPagsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCantPagsFocusLost
        txtCantPags.setBackground(Color.white);
        txtCantPags.setForeground(Color.black);
    }//GEN-LAST:event_txtCantPagsFocusLost

    private void txtIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9' && caracter != '\b') {
            evt.consume();
        }
    }//GEN-LAST:event_txtIsbnKeyTyped

    private void txtYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9' && caracter != '\b' || txtYear.getText().length() == 4){
            evt.consume();
        }
    }//GEN-LAST:event_txtYearKeyTyped

    private void txtCantPagsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantPagsKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9' && caracter != '\b' || txtYear.getText().length() == 4){
            evt.consume();
        }
    }//GEN-LAST:event_txtCantPagsKeyTyped

    private void btnPortadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPortadaActionPerformed
        int resultado;
        PortadaEdit portada = new PortadaEdit();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");
        portada.fchPortada.setFileFilter(filtro);
        resultado =  portada.fchPortada.showOpenDialog(null);
        if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero = portada.fchPortada.getSelectedFile();
            try {
                ImageIcon icon = new ImageIcon(fichero.toString());
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblPortada.getWidth(), lblPortada.getHeight(), Image.SCALE_DEFAULT));
                lblPortada.setText(null);
                lblPortada.setIcon(icono);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error abriendo la imagen" + e);
            }
        }
    }//GEN-LAST:event_btnPortadaActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter != '\b' && (!Character.isLetter(caracter)) && caracter != KeyEvent.VK_SPACE) {
            evt.consume();
        } else {
            String cad = ("" + caracter).toUpperCase();
            caracter = cad.charAt(0);
            evt.setKeyChar(caracter);
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtLugarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter != '\b' && (!Character.isLetter(caracter)) && caracter!= KeyEvent.VK_SPACE) {
            evt.consume();
        } else {
            if (Character.isLowerCase(caracter)) {
                String cad = ("" + caracter).toUpperCase();
                caracter = cad.charAt(0);
                evt.setKeyChar(caracter);
            }
        }
    }//GEN-LAST:event_txtLugarKeyTyped

    private void txtCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodeFocusGained
        txtCode.setBackground(Color.darkGray);
        txtCode.setForeground(Color.white);
        txtCode.selectAll();
    }//GEN-LAST:event_txtCodeFocusGained

    private void txtCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodeFocusLost
        txtCode.setBackground(Color.white);
        txtCode.setForeground(Color.black);
    }//GEN-LAST:event_txtCodeFocusLost

    private void txtCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            cboTipoLibro.requestFocus();
        }
    }//GEN-LAST:event_txtCodeKeyPressed

    private void txtCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeKeyTyped
        char caracter = evt.getKeyChar();
        if (caracter != KeyEvent.VK_PERIOD && txtCode.getText().length() >= 20 && caracter < '0' || caracter > '9' && (!Character.isLetter(caracter)) || txtCode.getText().length() >= 20) {
            evt.consume();
        } else {
            if (Character.isLowerCase(caracter)) {
                String cad = ("" + caracter).toUpperCase();
                caracter = cad.charAt(0);
                evt.setKeyChar(caracter);
            }
        }
    }//GEN-LAST:event_txtCodeKeyTyped

    private void cboTipoLibroPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboTipoLibroPopupMenuWillBecomeInvisible
        txaContenidos.requestFocus();
    }//GEN-LAST:event_cboTipoLibroPopupMenuWillBecomeInvisible

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
        autoredit = new FrmAutorEdit();
        Dimension ds = Main.dtpMain.getSize();
        Dimension fs = autoredit.getSize();
        autoredit.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
        txtNombre.setEnabled(false);
        btnAutores.setEnabled(false);
        cboAutores.setEnabled(false);
        cboEditorial.setEnabled(false);
        txtIsbn.setEnabled(false);
        btnPortada.setEnabled(false);
        cboMateria.setEnabled(false);
        txtLugar.setEnabled(false);
        txtYear.setEnabled(false);
        txtCantPags.setEnabled(false);
        txtCode.setEnabled(false);
        cboTipoLibro.setEnabled(false);
        txaContenidos.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnSalir.setEnabled(false);
        autoredit.show();
    }//GEN-LAST:event_btnAutoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAutores;
    public static javax.swing.JButton btnGuardar;
    public static javax.swing.JButton btnPortada;
    public static javax.swing.JButton btnSalir;
    public static javax.swing.JComboBox<String> cboAutores;
    public static javax.swing.JComboBox<String> cboEditorial;
    public static javax.swing.JComboBox<String> cboMateria;
    public static javax.swing.JComboBox<String> cboTipoLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblPortada;
    public static javax.swing.JTextArea txaContenidos;
    public static javax.swing.JTextField txtCantPags;
    public static javax.swing.JTextField txtCode;
    public static javax.swing.JTextField txtIsbn;
    public static javax.swing.JTextField txtLugar;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
