/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Functions.Reportes;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bryyv
 */
public class JIFListarLibros extends javax.swing.JInternalFrame {
    DefaultTableModel modelo;
    Functions.Functions cnn = new Functions.Functions();
    
    /**
     * Creates new form JIFListarLibros
     */
    public JIFListarLibros() {
        modelo = new DefaultTableModel(null, getColumnas());
        setFilas();
        initComponents();
    }
    private String[] getColumnas() {
        String columna[] = new String[] {"Código", "Título", "Prestado a", "Fecha"};
        return columna;
    }
    
    
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    
    private void setFilas() {
        try {
            String sql = "SELECT DISTINCT libro.lib_id, libro.titulo, usuario.apellidos || ' ' || usuario.nombres, to_char(prestamo.fprestamo, 'YYYY/MM/DD') AS fecha FROM libro, usuario, prestamo, detalle_prestamo WHERE detalle_prestamo.lib_id = libro.lib_id AND prestamo.usu_dni = usuario.usu_dni ORDER BY fecha DESC";
            PreparedStatement ps = cnn.getCnn().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            Object datos[] = new Object[4];
            while (rs.next()) {
                for (int i = 0; i < 4; i++) {
                    datos[i] = rs.getObject(i + 1);
                }
                modelo.addRow(datos);
            }
            rs.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbLibros = new javax.swing.JTable();
        btnExportar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Lista de libros prestados");

        tbLibros.setModel(modelo);
        jScrollPane1.setViewportView(tbLibros);

        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/imprimir.png"))); // NOI18N
        btnExportar.setText("PDF");
        btnExportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addComponent(btnExportar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        Reportes re = new Reportes();
        String dir_current = System.getProperty("user.dir");
        String ruta = dir_current + "/reporte/libros_prestados.jasper";
        JFileChooser fc = new JFileChooser();
        fc.setFileFilter(new FileNameExtensionFilter("todos los archivos *.pdf", "pdf", "PDF"));
        int selection = fc.showSaveDialog(null);
        try {
            if (selection == JFileChooser.APPROVE_OPTION) {
                JOptionPane.showMessageDialog(null, "Esto puede tardar unos segundos, espere por favor", "Estamos generando el reporte", JOptionPane.WARNING_MESSAGE);
                File JFC = fc.getSelectedFile();
                String PATH = JFC.getAbsolutePath();
                try (PrintWriter printwriter = new PrintWriter(JFC)){
                    printwriter.print(ruta);
                } catch (HeadlessException ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
                re.reportesPDF(ruta, PATH);
                if (!(PATH.endsWith(".pdf"))) {
                    File temp = new File(PATH + ".pdf");
                    JFC.renameTo(temp);
                }
                JOptionPane.showMessageDialog(null, "Documento exportado exitosamente", "Guardado exitoso", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLibros;
    // End of variables declaration//GEN-END:variables
}
