/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Functions.fondMain;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;

/**
 *
 * @author Bryyv
 */
public class Main extends javax.swing.JFrame {
    JIFAutorAdd autoradd;
    JIFAutorEdit autoredit;
    JIFAutorShow autorshow;
    JIFBookAdd bookadd;
    JIFBookEdit bookedit;
    JIFBookShow bookshow;
    JIFEditorialAdd editorialadd;
    JIFEditorialEdit editorialedit;
    JIFEditorialShow editorialshow;
    JIFLookBook_Autor look_book_autor;
    JIFLookBook_Editorial look_book_editorial;
    JIFLookBook_Materia look_book_materia;
    JIFLookBook_Name look_book_name;
    JIFMateriaAdd materiaadd;
    JIFMateriaEdit materiaedit;
    JIFMateriaShow materiashow;
    JIFUserAdd useradd;
    JIFUserEdit useredit;
    JIFUserQuest userquest;
    JIFUserShow usershow;
    JIFPrestamo prestamo;
    JIFPersonalAdd personaladd;
    JIFPersonalEdit personaledit;
    JIFPersonalShow personalshow;
    JIFPersonalQuest personalquest;
    JIFDevolucion devolucion;
    JIFListarLibros libros_prestados;
    public InputStream main = this.getClass().getResourceAsStream("/Resources/fondo_.jpg");

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        cargarImagen(dtpMain, main);
    }
    
    private void cargarImagen(javax.swing.JDesktopPane jDeskp, InputStream fileImagen) {
        try {
            BufferedImage image = ImageIO.read(fileImagen);
            jDeskp.setBorder(new fondMain(image));
        } catch (Exception e) {
            System.out.println("Imagen no disponible");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dtpMain = new javax.swing.JDesktopPane();
        barMain = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mitSalir1 = new javax.swing.JMenuItem();
        mitSalir = new javax.swing.JMenuItem();
        mnPrestamo = new javax.swing.JMenu();
        mitPrestamo = new javax.swing.JMenuItem();
        mitDevolucion = new javax.swing.JMenuItem();
        mitListarPrestamos = new javax.swing.JMenuItem();
        mnQuest = new javax.swing.JMenu();
        mnBooks = new javax.swing.JMenu();
        mitByBook = new javax.swing.JMenuItem();
        mitByAutor = new javax.swing.JMenuItem();
        mitByEditorial = new javax.swing.JMenuItem();
        mitByMateria = new javax.swing.JMenuItem();
        mitUser = new javax.swing.JMenuItem();
        mitAutor = new javax.swing.JMenuItem();
        mitEditorial = new javax.swing.JMenuItem();
        mitMateria = new javax.swing.JMenuItem();
        mnAdd = new javax.swing.JMenu();
        mitAddBook = new javax.swing.JMenuItem();
        mitAddUser = new javax.swing.JMenuItem();
        mitAddAutor = new javax.swing.JMenuItem();
        mitAddEditorial = new javax.swing.JMenuItem();
        mitAddMateria = new javax.swing.JMenuItem();
        mnEdit = new javax.swing.JMenu();
        mitEditBook = new javax.swing.JMenuItem();
        mitEditUser = new javax.swing.JMenuItem();
        mitEditAutor = new javax.swing.JMenuItem();
        mitEditEditorial = new javax.swing.JMenuItem();
        mitEditMateria = new javax.swing.JMenuItem();
        mnShow = new javax.swing.JMenu();
        mitShowBook = new javax.swing.JMenuItem();
        mitShowUser = new javax.swing.JMenuItem();
        mitShowAutor = new javax.swing.JMenuItem();
        mitShowEditorial = new javax.swing.JMenuItem();
        mitShowMateria = new javax.swing.JMenuItem();
        mnPersonal = new javax.swing.JMenu();
        mitAddPersonal = new javax.swing.JMenuItem();
        mitQuestPersonal = new javax.swing.JMenuItem();
        mitShowPersonal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Booklend");
        setExtendedState(4);
        setMinimumSize(new java.awt.Dimension(900, 550));
        setName("FrmMain"); // NOI18N

        javax.swing.GroupLayout dtpMainLayout = new javax.swing.GroupLayout(dtpMain);
        dtpMain.setLayout(dtpMainLayout);
        dtpMainLayout.setHorizontalGroup(
            dtpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        dtpMainLayout.setVerticalGroup(
            dtpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        mnFile.setText("Archivo");

        mitSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/cancelar.png"))); // NOI18N
        mitSalir1.setText("Cerrar Sesión");
        mitSalir1.setContentAreaFilled(false);
        mitSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSalir1ActionPerformed(evt);
            }
        });
        mnFile.add(mitSalir1);

        mitSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mitSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logout.png"))); // NOI18N
        mitSalir.setText("Salir");
        mitSalir.setContentAreaFilled(false);
        mitSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSalirActionPerformed(evt);
            }
        });
        mnFile.add(mitSalir);

        barMain.add(mnFile);

        mnPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/libros.png"))); // NOI18N
        mnPrestamo.setText("Préstamo");

        mitPrestamo.setText("Registrar préstamo");
        mitPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPrestamoActionPerformed(evt);
            }
        });
        mnPrestamo.add(mitPrestamo);

        mitDevolucion.setText("Registrar devolución");
        mitDevolucion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDevolucionActionPerformed(evt);
            }
        });
        mnPrestamo.add(mitDevolucion);

        mitListarPrestamos.setText("Listar libros prestados");
        mitListarPrestamos.setToolTipText("");
        mitListarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitListarPrestamosActionPerformed(evt);
            }
        });
        mnPrestamo.add(mitListarPrestamos);

        barMain.add(mnPrestamo);

        mnQuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/buscar.png"))); // NOI18N
        mnQuest.setText("Búsqueda");

        mnBooks.setText("Libros");
        mnBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        mitByBook.setText("Por Título");
        mitByBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitByBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitByBookActionPerformed(evt);
            }
        });
        mnBooks.add(mitByBook);

        mitByAutor.setText("Por Autor");
        mitByAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitByAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitByAutorActionPerformed(evt);
            }
        });
        mnBooks.add(mitByAutor);

        mitByEditorial.setText("Por Editorial");
        mitByEditorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitByEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitByEditorialActionPerformed(evt);
            }
        });
        mnBooks.add(mitByEditorial);

        mitByMateria.setText("Por Materia");
        mitByMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitByMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitByMateriaActionPerformed(evt);
            }
        });
        mnBooks.add(mitByMateria);

        mnQuest.add(mnBooks);

        mitUser.setText("Usuario");
        mitUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitUserActionPerformed(evt);
            }
        });
        mnQuest.add(mitUser);

        mitAutor.setText("Autor");
        mitAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAutorActionPerformed(evt);
            }
        });
        mnQuest.add(mitAutor);

        mitEditorial.setText("Editorial");
        mitEditorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitEditorialActionPerformed(evt);
            }
        });
        mnQuest.add(mitEditorial);

        mitMateria.setText("Materia");
        mitMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitMateriaActionPerformed(evt);
            }
        });
        mnQuest.add(mitMateria);

        barMain.add(mnQuest);

        mnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/agregar.png"))); // NOI18N
        mnAdd.setText("Añadir");

        mitAddBook.setText("Nuevo Libro");
        mitAddBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAddBookActionPerformed(evt);
            }
        });
        mnAdd.add(mitAddBook);

        mitAddUser.setText("Nuevo Usuario");
        mitAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAddUserActionPerformed(evt);
            }
        });
        mnAdd.add(mitAddUser);

        mitAddAutor.setText("Nuevo Autor");
        mitAddAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitAddAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAddAutorActionPerformed(evt);
            }
        });
        mnAdd.add(mitAddAutor);

        mitAddEditorial.setText("Nueva Editorial");
        mitAddEditorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitAddEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAddEditorialActionPerformed(evt);
            }
        });
        mnAdd.add(mitAddEditorial);

        mitAddMateria.setText("Nueva Materia");
        mitAddMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitAddMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAddMateriaActionPerformed(evt);
            }
        });
        mnAdd.add(mitAddMateria);

        barMain.add(mnAdd);

        mnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/editar.png"))); // NOI18N
        mnEdit.setText("Modificar");

        mitEditBook.setText("Datos de Libro");
        mitEditBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitEditBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitEditBookActionPerformed(evt);
            }
        });
        mnEdit.add(mitEditBook);

        mitEditUser.setText("Datos de Usuario existente");
        mitEditUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitEditUserActionPerformed(evt);
            }
        });
        mnEdit.add(mitEditUser);

        mitEditAutor.setText("Autor");
        mitEditAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitEditAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitEditAutorActionPerformed(evt);
            }
        });
        mnEdit.add(mitEditAutor);

        mitEditEditorial.setText("Editorial");
        mitEditEditorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitEditEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitEditEditorialActionPerformed(evt);
            }
        });
        mnEdit.add(mitEditEditorial);

        mitEditMateria.setText("Materia");
        mitEditMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitEditMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitEditMateriaActionPerformed(evt);
            }
        });
        mnEdit.add(mitEditMateria);

        barMain.add(mnEdit);

        mnShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/listar.png"))); // NOI18N
        mnShow.setText("Listar");

        mitShowBook.setText("Mostrar Libros");
        mitShowBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitShowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitShowBookActionPerformed(evt);
            }
        });
        mnShow.add(mitShowBook);

        mitShowUser.setText("Mostrar Usuarios");
        mitShowUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitShowUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitShowUserActionPerformed(evt);
            }
        });
        mnShow.add(mitShowUser);

        mitShowAutor.setText("Mostrar Autores");
        mitShowAutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitShowAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitShowAutorActionPerformed(evt);
            }
        });
        mnShow.add(mitShowAutor);

        mitShowEditorial.setText("Mostrar Editoriales");
        mitShowEditorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitShowEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitShowEditorialActionPerformed(evt);
            }
        });
        mnShow.add(mitShowEditorial);

        mitShowMateria.setText("Mostrar Materias");
        mitShowMateria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitShowMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitShowMateriaActionPerformed(evt);
            }
        });
        mnShow.add(mitShowMateria);

        barMain.add(mnShow);

        mnPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/personal.png"))); // NOI18N
        mnPersonal.setText("Colaboradores");

        mitAddPersonal.setText("Añadir colaborador");
        mitAddPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitAddPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAddPersonalActionPerformed(evt);
            }
        });
        mnPersonal.add(mitAddPersonal);

        mitQuestPersonal.setText("Buscar colaborador");
        mitQuestPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitQuestPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitQuestPersonalActionPerformed(evt);
            }
        });
        mnPersonal.add(mitQuestPersonal);

        mitShowPersonal.setText("Listar colaboradores");
        mitShowPersonal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mitShowPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitShowPersonalActionPerformed(evt);
            }
        });
        mnPersonal.add(mitShowPersonal);

        barMain.add(mnPersonal);

        setJMenuBar(barMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dtpMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitSalirActionPerformed

    private void mitByBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitByBookActionPerformed
        if (look_book_name == null || look_book_name.isClosed()) {
            look_book_name = new JIFLookBook_Name();
            dtpMain.add(look_book_name);
            Dimension ds = dtpMain.getSize();
            Dimension fs = look_book_name.getSize();
            look_book_name.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            try {
                look_book_name.setSelected(true);
                look_book_name.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            look_book_name.show();
        }
    }//GEN-LAST:event_mitByBookActionPerformed

    private void mitByAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitByAutorActionPerformed
        if (look_book_autor == null || look_book_autor.isClosed()) {
            look_book_autor = new JIFLookBook_Autor();
            dtpMain.add(look_book_autor);
            Dimension ds = dtpMain.getSize();
            Dimension fs = look_book_autor.getSize();
            look_book_autor.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            try {
                look_book_autor.setSelected(true);
                look_book_autor.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            look_book_autor.show();
        }
    }//GEN-LAST:event_mitByAutorActionPerformed

    private void mitByEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitByEditorialActionPerformed
        if (look_book_editorial == null || look_book_editorial.isClosed()) {
            look_book_editorial = new JIFLookBook_Editorial();
            dtpMain.add(look_book_editorial);
            Dimension ds = dtpMain.getSize();
            Dimension fs = look_book_editorial.getSize();
            look_book_editorial.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            try {
                look_book_editorial.setSelected(true);
                look_book_editorial.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            look_book_editorial.show();
        }
    }//GEN-LAST:event_mitByEditorialActionPerformed

    private void mitByMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitByMateriaActionPerformed
        if (look_book_materia == null || look_book_materia.isClosed()) {
            look_book_materia = new JIFLookBook_Materia();
            dtpMain.add(look_book_materia);
            Dimension ds = dtpMain.getSize();
            Dimension fs = look_book_materia.getSize();
            look_book_materia.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            try {
                look_book_materia.setSelected(true);
                look_book_materia.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            look_book_materia.show();
        }
    }//GEN-LAST:event_mitByMateriaActionPerformed

    private void mitUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitUserActionPerformed
        if (useredit == null || useredit.isClosed()) {
            useredit = new JIFUserEdit();
            dtpMain.add(useredit);
            Dimension ds = dtpMain.getSize();
            Dimension fs = useredit.getSize();
            useredit.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            useredit.show();
        }
    }//GEN-LAST:event_mitUserActionPerformed

    private void mitAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAutorActionPerformed
        if (autorshow == null || autorshow.isClosed()) {
            autorshow = new JIFAutorShow();
            dtpMain.add(autorshow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = autorshow.getSize();
            autorshow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            autorshow.show();
        }
    }//GEN-LAST:event_mitAutorActionPerformed

    private void mitEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitEditorialActionPerformed
        if (editorialshow == null || editorialshow.isClosed()) {
            editorialshow = new JIFEditorialShow();
            dtpMain.add(editorialshow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = editorialshow.getSize();
            editorialshow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            editorialshow.show();
        }
    }//GEN-LAST:event_mitEditorialActionPerformed

    private void mitMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitMateriaActionPerformed
        if (materiashow == null || materiashow.isClosed()) {
            materiashow = new JIFMateriaShow();
            dtpMain.add(materiashow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = materiashow.getSize();
            materiashow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            materiashow.show();
        }
    }//GEN-LAST:event_mitMateriaActionPerformed

    private void mitAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAddBookActionPerformed
        if (bookadd == null || bookadd.isClosed()) {
            bookadd = new JIFBookAdd();
            dtpMain.add(bookadd);
            Dimension ds = dtpMain.getSize();
            Dimension fs = bookadd.getSize();
            bookadd.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            bookadd.show();
        }
    }//GEN-LAST:event_mitAddBookActionPerformed

    private void mitAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAddUserActionPerformed
        if (useradd == null || useradd.isClosed()) {
            useradd = new JIFUserAdd();
            dtpMain.add(useradd);
            Dimension ds = dtpMain.getSize();
            Dimension fs = useradd.getSize();
            useradd.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            useradd.show();
        }
    }//GEN-LAST:event_mitAddUserActionPerformed

    private void mitAddAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAddAutorActionPerformed
        if (autoradd == null || autoradd.isClosed()) {
            autoradd = new JIFAutorAdd();
            dtpMain.add(autoradd);
            Dimension ds = dtpMain.getSize();
            Dimension fs = autoradd.getSize();
            autoradd.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            autoradd.show();
        }
    }//GEN-LAST:event_mitAddAutorActionPerformed

    private void mitAddEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAddEditorialActionPerformed
        if (editorialadd == null || editorialadd.isClosed()) {
            editorialadd = new JIFEditorialAdd();
            dtpMain.add(editorialadd);
            Dimension ds = dtpMain.getSize();
            Dimension fs = editorialadd.getSize();
            editorialadd.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            editorialadd.show();
        }
    }//GEN-LAST:event_mitAddEditorialActionPerformed

    private void mitAddMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAddMateriaActionPerformed
        if (materiaadd == null || materiaadd.isClosed()) {
            materiaadd = new JIFMateriaAdd();
            dtpMain.add(materiaadd);
            Dimension ds = dtpMain.getSize();
            Dimension fs = materiaadd.getSize();
            materiaadd.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            materiaadd.show();
        }
    }//GEN-LAST:event_mitAddMateriaActionPerformed

    private void mitEditBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitEditBookActionPerformed
        if (look_book_name == null || look_book_name.isClosed()) {
            look_book_name = new JIFLookBook_Name();
            dtpMain.add(look_book_name);
            Dimension ds = dtpMain.getSize();
            Dimension fs = look_book_name.getSize();
            look_book_name.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            look_book_name.show();
        }
    }//GEN-LAST:event_mitEditBookActionPerformed

    private void mitEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitEditUserActionPerformed
        if (userquest == null || userquest.isClosed()) {
            userquest = new JIFUserQuest();
            dtpMain.add(userquest);
            Dimension ds = dtpMain.getSize();
            Dimension fs = userquest.getSize();
            userquest.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            userquest.show();
        }
    }//GEN-LAST:event_mitEditUserActionPerformed

    private void mitEditAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitEditAutorActionPerformed
        if (autorshow == null || autorshow.isClosed()) {
            autorshow = new JIFAutorShow();
            dtpMain.add(autorshow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = autorshow.getSize();
            autorshow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            autorshow.show();
        }
    }//GEN-LAST:event_mitEditAutorActionPerformed

    private void mitEditEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitEditEditorialActionPerformed
        if (editorialshow == null || editorialshow.isClosed()) {
            editorialshow = new JIFEditorialShow();
            dtpMain.add(editorialshow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = editorialshow.getSize();
            editorialshow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            editorialshow.show();
        }
    }//GEN-LAST:event_mitEditEditorialActionPerformed

    private void mitEditMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitEditMateriaActionPerformed
        if (materiashow == null || materiashow.isClosed()) {
            materiashow = new JIFMateriaShow();
            dtpMain.add(materiashow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = materiashow.getSize();
            materiashow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            materiashow.show();
        }
    }//GEN-LAST:event_mitEditMateriaActionPerformed

    private void mitShowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitShowBookActionPerformed
        if (bookshow == null || bookshow.isClosed()) {
            bookshow = new JIFBookShow();
            dtpMain.add(bookshow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = bookshow.getSize();
            bookshow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            try {
                bookshow.setSelected(true);
                bookshow.setMaximum(true);
            } catch (PropertyVetoException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            bookshow.show();
        }
    }//GEN-LAST:event_mitShowBookActionPerformed

    private void mitShowUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitShowUserActionPerformed
        if (usershow == null || usershow.isClosed()) {
            usershow = new JIFUserShow();
            dtpMain.add(usershow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = usershow.getSize();
            usershow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            usershow.show();
        }
    }//GEN-LAST:event_mitShowUserActionPerformed

    private void mitShowAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitShowAutorActionPerformed
        if (autorshow == null || autorshow.isClosed()) {
            autorshow = new JIFAutorShow();
            dtpMain.add(autorshow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = autorshow.getSize();
            autorshow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            autorshow.show();
        }
    }//GEN-LAST:event_mitShowAutorActionPerformed

    private void mitShowEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitShowEditorialActionPerformed
        if (editorialshow == null || editorialshow.isClosed()) {
            editorialshow = new JIFEditorialShow();
            dtpMain.add(editorialshow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = editorialshow.getSize();
            editorialshow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            editorialshow.show();
        }
    }//GEN-LAST:event_mitShowEditorialActionPerformed

    private void mitShowMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitShowMateriaActionPerformed
        if (materiashow == null || materiashow.isClosed()) {
            materiashow = new JIFMateriaShow();
            dtpMain.add(materiashow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = materiashow.getSize();
            materiashow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            materiashow.show();
        }
    }//GEN-LAST:event_mitShowMateriaActionPerformed

    private void mitPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPrestamoActionPerformed
        if (prestamo == null || prestamo.isClosed()) {
            prestamo = new JIFPrestamo();
            dtpMain.add(prestamo);
            Dimension ds = dtpMain.getSize();
            Dimension fs = prestamo.getSize();
            prestamo.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            prestamo.show();
        }
    }//GEN-LAST:event_mitPrestamoActionPerformed

    private void mitAddPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAddPersonalActionPerformed
        if (personaladd == null || personaladd.isClosed()) {
            personaladd = new JIFPersonalAdd();
            dtpMain.add(personaladd);
            Dimension ds = dtpMain.getSize();
            Dimension fs = personaladd.getSize();
            personaladd.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            personaladd.show();
        }
    }//GEN-LAST:event_mitAddPersonalActionPerformed

    private void mitQuestPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitQuestPersonalActionPerformed
        if (personalquest == null || personalquest.isClosed()) {
            personalquest = new JIFPersonalQuest();
            dtpMain.add(personalquest);
            Dimension ds = dtpMain.getSize();
            Dimension fs = personalquest.getSize();
            personalquest.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            personalquest.show();
        }
    }//GEN-LAST:event_mitQuestPersonalActionPerformed

    private void mitShowPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitShowPersonalActionPerformed
        if (personalshow == null || personalshow.isClosed()) {
            personalshow = new JIFPersonalShow();
            dtpMain.add(personalshow);
            Dimension ds = dtpMain.getSize();
            Dimension fs = personalshow.getSize();
            personalshow.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            personalshow.show();
        }
    }//GEN-LAST:event_mitShowPersonalActionPerformed

    private void mitDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDevolucionActionPerformed
        if (devolucion == null || devolucion.isClosed()) {
            devolucion = new JIFDevolucion();
            dtpMain.add(devolucion);
            Dimension ds = dtpMain.getSize();
            Dimension fs = devolucion.getSize();
            devolucion.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            devolucion.show();
        }
    }//GEN-LAST:event_mitDevolucionActionPerformed

    private void mitSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSalir1ActionPerformed
        this.dispose();
        Presentation.Acceso acceso = new Presentation.Acceso();
        acceso.setVisible(true);
    }//GEN-LAST:event_mitSalir1ActionPerformed

    private void mitListarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitListarPrestamosActionPerformed
        if (libros_prestados == null || libros_prestados.isClosed()) {
            libros_prestados = new JIFListarLibros();
            dtpMain.add(libros_prestados);
            Dimension ds = dtpMain.getSize();
            Dimension fs = libros_prestados.getSize();
            libros_prestados.setLocation((ds.width - fs.width) / 2, (ds.height - fs.height) / 2);
            libros_prestados.show();
        }
    }//GEN-LAST:event_mitListarPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PortadaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PortadaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PortadaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PortadaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        new Thread(new Credits()).start();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMain;
    public static javax.swing.JDesktopPane dtpMain;
    private javax.swing.JMenuItem mitAddAutor;
    private javax.swing.JMenuItem mitAddBook;
    private javax.swing.JMenuItem mitAddEditorial;
    private javax.swing.JMenuItem mitAddMateria;
    private javax.swing.JMenuItem mitAddPersonal;
    private javax.swing.JMenuItem mitAddUser;
    private javax.swing.JMenuItem mitAutor;
    private javax.swing.JMenuItem mitByAutor;
    private javax.swing.JMenuItem mitByBook;
    private javax.swing.JMenuItem mitByEditorial;
    private javax.swing.JMenuItem mitByMateria;
    private javax.swing.JMenuItem mitDevolucion;
    private javax.swing.JMenuItem mitEditAutor;
    private javax.swing.JMenuItem mitEditBook;
    private javax.swing.JMenuItem mitEditEditorial;
    private javax.swing.JMenuItem mitEditMateria;
    private javax.swing.JMenuItem mitEditUser;
    private javax.swing.JMenuItem mitEditorial;
    private javax.swing.JMenuItem mitListarPrestamos;
    private javax.swing.JMenuItem mitMateria;
    private javax.swing.JMenuItem mitPrestamo;
    private javax.swing.JMenuItem mitQuestPersonal;
    private javax.swing.JMenuItem mitSalir;
    private javax.swing.JMenuItem mitSalir1;
    private javax.swing.JMenuItem mitShowAutor;
    private javax.swing.JMenuItem mitShowBook;
    private javax.swing.JMenuItem mitShowEditorial;
    private javax.swing.JMenuItem mitShowMateria;
    private javax.swing.JMenuItem mitShowPersonal;
    private javax.swing.JMenuItem mitShowUser;
    private javax.swing.JMenuItem mitUser;
    private javax.swing.JMenu mnAdd;
    private javax.swing.JMenu mnBooks;
    private javax.swing.JMenu mnEdit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnPersonal;
    private javax.swing.JMenu mnPrestamo;
    private javax.swing.JMenu mnQuest;
    private javax.swing.JMenu mnShow;
    // End of variables declaration//GEN-END:variables
}
